
```{r cargadatos, include=FALSE }
library(leaflet)
library(leaflet.extras)
```

```{r mapasbase, include=FALSE}
#Carga de mapas base
basemap <- leaflet() %>%
  # add different provider tiles
  addProviderTiles(
    "OpenStreetMap",
    # give the layer a name
    group = "OpenStreetMap"
    ) %>%
  addProviderTiles(
    "Esri.WorldImagery",
    group = "Satelital"
  ) %>%
  # add a layers control
  addLayersControl(
    baseGroups = c(
      "Satelital", "OpenStreetMap"
    ),
    # position it on the topleft
    position = "topleft"
  )
```

```{r cargaicono-mapa, include=FALSE}
```


```{r cargaicono, echo = FALSE}
#Carga de icono para ubicación
# Make a list of icons. We'll index into it based on name.
greenLeafIcon <- makeIcon(
  iconUrl = "https://github.com/MontserratJB/Ubicacion_Municipalidad/blob/main/app/monumental.png?raw=true",
  iconWidth = 30, iconHeight = 35,
  iconAnchorX = 22, iconAnchorY = 22
)

m <- basemap %>%
  addMarkers(lng=-84.05247, lat=9.93316, icon=greenLeafIcon, label="Municipalidad de Montes de Oca")
#Mapa
m
```




